// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy71E9LPf0XOhzwXZezzZV-oDd68CkpDg',
    appId: '1:706892114240:web:97782857a7348af97cf2a5',
    messagingSenderId: '706892114240',
    projectId: 'new-firebase-setup-e0f49',
    authDomain: 'new-firebase-setup-e0f49.firebaseapp.com',
    storageBucket: 'new-firebase-setup-e0f49.appspot.com',
    measurementId: 'G-VLYH171DNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc-Uh6f8uA9Ag3BXQwdmmR2AkXCUYKAGo',
    appId: '1:706892114240:android:5a2a19c7a9eaff0c7cf2a5',
    messagingSenderId: '706892114240',
    projectId: 'new-firebase-setup-e0f49',
    storageBucket: 'new-firebase-setup-e0f49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfKBLI-1mBp1mb2Isrvb2j_Txb_Xn8mQs',
    appId: '1:706892114240:ios:0df67f0b92b79cfd7cf2a5',
    messagingSenderId: '706892114240',
    projectId: 'new-firebase-setup-e0f49',
    storageBucket: 'new-firebase-setup-e0f49.appspot.com',
    androidClientId: '706892114240-b36p6ctk4s33ahoj2i8blpvarv7tprrn.apps.googleusercontent.com',
    iosClientId: '706892114240-0003opmbk1d754frsudt4f7nplaq0kci.apps.googleusercontent.com',
    iosBundleId: 'com.example.userBuddies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfKBLI-1mBp1mb2Isrvb2j_Txb_Xn8mQs',
    appId: '1:706892114240:ios:b1df4e8a4b8b061f7cf2a5',
    messagingSenderId: '706892114240',
    projectId: 'new-firebase-setup-e0f49',
    storageBucket: 'new-firebase-setup-e0f49.appspot.com',
    androidClientId: '706892114240-b36p6ctk4s33ahoj2i8blpvarv7tprrn.apps.googleusercontent.com',
    iosClientId: '706892114240-qb18v8kk6ovbsjk7qqdcsvo0er4r3udp.apps.googleusercontent.com',
    iosBundleId: 'com.example.userBuddies.RunnerTests',
  );
}
